language: android

before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- sdkmanager tools


jdk:
  - oraclejdk8

install:
  - ./gradlew rxusecase:assemble rxusecase:test
