language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-27.0.2
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
licenses:
    - 'android-sdk-license-.+'

before_script:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

script:
  - ./gradlew rxusecase:assemble rxusecase:test
